export const config ={
"Buyers_rebate_of_gross_commission":"Y",
"Closing_cost":"Y",
"End_of_summer_special":"N",
"Estimated_agent_commission":"N",
"Free_home_warranty":"Y",
"Is_Cluster":"Yes",
"Towards_moving_cost": "N",
"about_us_image": "",
"admin_email_sign": "<br />\r\n<br />",
"appstore_app_link": "http://appstore",
"appstore_logo": "201701180050301575267930-app.png",
"bing_geocode_api_url": "",
"bing_map_api_url": "",
"bing_map_key": "",
"blocked_email": "",
"blocked_ip": "",
"browser_title": "",
"contact_address": "",
"contact_email": "",
"contact_number": "",
"copyright_text": "",
"data_domain": "",
"deal_score": "Yes",
"default_page_size": "100",
"disable_email": "No",
"email_admin": "test.thatsend@gmail.com",
"email_admin_title": "Thats End Developer",
"email_developer": "test.thatsend@gmail.com",
"email_header": "201709140617451519888365-email-header.jpg",
"email_lead": "test.thatsend@gmail.com",
"email_lead_title": "Ref Code Lead",
"email_registration": "test.thatsend@gmail.com",
"email_registration_title": "Site Registration",
"email_sign": "<p>With best regards,<br />",
"email_support": "test.thatsend@gmail.com",
"email_webmaster": "test.thatsend@gmail.com",
"email_webmaster_title": "Site Webmaster",
"enable_admin_help": "No",
"enable_recurring": "No",
"enable_serverside_validation": "Yes",
"enable_word_censoring": "Yes",
"facebook_app_id": "",
"facebook_app_secret_key": "",
"families_of_launch_text": "",
"featured_listing_deal_score": "Yes",
"footer_bottom_content": "",
"footer_serving": "Serving<br /> Since<br /> 2001",
"google_analytics": "",
"google_geocode_api_last_used": "2022-07-23",
"google_geocode_api_total_request": "1",
"google_geocode_api_usage_limit": "2500",
"google_map_key": "",
"google_map_url": "",
"google_static_map_url": "",
"google_tracking_code": "",
"goolge_geocode_api_url": "",
"gplus_app_id": "",
"gplus_app_secret_key": "",
"heremap_geocode_api_last_used": "2022-07-23",
"heremap_geocode_api_total_request": "37",
"heremap_geocode_api_usage_limit": "200000",
"home_value_background_image": "201601272258471470846527-homepage-bg.jpg",
"hp_featured_listings": "",
"idx_api_flag": "false",
"idx_api_key": "",
"idxapi_url": "",
"launch_news_image": "201604190157331512051553-news.jpg",
"listing_disclaimer": "",
"listing_max_display": "99999",
"listing_per_page": "5",
"lseo_mob_openhouse_detail_prefix_price": "",
"lseo_mob_sale_detail_prefix_price": "",
"lseo_openhouse_city_enable_sitemap": "",
"lseo_openhouse_detail_browser_title": "[AddressFull], MLS# [MLS], [City] [State] Open House",
"lseo_openhouse_detail_meta_desc": "[City] Open House at [AddressFull], MLS# [MLS] - Find all details of listing at [City] [State] with [SiteTitle]",
"lseo_openhouse_detail_meta_keyword": "[City] Open House, Open House in Zip Code [Zipcode], MLS# [MLS], [City] Open House, [City], [City] [State]",
"lseo_openhouse_detail_page_desc": "[City] Open House.",
"lseo_openhouse_detail_page_title": "[AddressFull]",
"lseo_openhouse_detail_prefix_price": "",
"lseo_openhouse_detail_sub_title": "Open Houses in [City]",
"lseo_openhouse_suburb_enable_sitemap": "",
"lseo_openhouse_zipcode_enable_sitemap": "",
"lseo_rent_detail_browser_title": "[AddressFull], MLS# [MLS], [City] [State] Homes For Rent",
"lseo_rent_detail_meta_desc": "[City] Homes For Rent at [AddressFull], MLS# [MLS] - Find all details of listing at [City] [State] with [SiteTitle]",
"lseo_rent_detail_meta_keyword": "[City] Homes For Rent, Homes for Rent in Zip Code [Zipcode], MLS# [MLS], [City] Homes For Rent, [City], [City] [State]",
"lseo_rent_detail_page_desc": "[City] Homes For Rent.",
"lseo_rent_detail_page_title": "[AddressFull]",
"lseo_rent_detail_prefix_price": "",
"lseo_rent_detail_sub_title": "Homes For Rent in [City]",
"lseo_sale_city_browser_title": "[City], [State] Homes For Sale, [City] Listings, [City] Homes For Sale",
"lseo_sale_city_enable_sitemap": "",
"lseo_sale_city_meta_desc": "[City], [State] Homes For Sale - Find listings and homes for sale in [City], [State].",
"lseo_sale_city_meta_keyword": "[City] [State] Homes For Sale, [City] Listings, [City] Homes For Sale",
"lseo_sale_city_page_desc": "[City], [State] Homes For Sale - Find listings and homes for sale in [City], [State].",
"lseo_sale_city_page_title": "[City], [State]",
"lseo_sale_detail_browser_title": "[Area] [City] Homes For Sale",
"lseo_sale_detail_meta_desc": "[City] Homes For Sale at [AddressFull], MLS# [MLS]",
"lseo_sale_detail_meta_keyword": "[City] Homes For Sale, Homes for Sale in Zip Code [Zipcode], MLS# [MLS], [City] Homes For Sale, [City], [City] [State]",
"lseo_sale_detail_page_desc": "[City] Homes for Sale.",
"lseo_sale_detail_page_title": "[AddressSmall]",
"lseo_sale_detail_prefix_price": "",
"lseo_sale_detail_sub_title": "Homes For Sale in [City]",
"lseo_sale_suburb_enable_sitemap": "",
"lseo_sale_zipcode_enable_sitemap": "",
"map_result_page_size": "600",
"map_type": "Google",
"mbl_map_page_size": "300",
"meta_common_keyword": "",
"meta_description": "",
"meta_developer": "",
"meta_keyword": "",
"meta_tag_additional": "",
"meta_update_all": "",
"mls_office_ids": "",
"neighborhood_guide_image": "201604210122321464188052-neighborhoods-head.jpg",
"neighborhood_image": "201604190157331495750553-neighborhoods.jpg",
"other_contact_address": "1,2,3,4",
"page_faq_custom_answer_code": "",
"page_faq_custom_question_code": "",
"page_faq_data": "",
"page_size": "10",
"pc_enable_recurring": "No",
"pc_signup_required_for_view_property_enable": "Yes",
"pc_total_page_allowed_before_registration": "2",
"pets_of_launch_text": "",
"playstore_app_link": "",
"playstore_logo": "201701180050301561567130-play.png",
"powered_by": "",
"prop_browse_city_list": "",
"prop_fet_city_list": "",
"prop_fet_zipcode_list": "",
"prop_recent_agent_id": "",
"prop_recent_city_list": "",
"prop_recent_zipcode_list": "",
"rebcalc_free_closing_costs_txt": "",
"rebcalc_free_closing_costs_value": "",
"rebcalc_free_home_warrenty_txt": "",
"rebcalc_free_home_warrenty_value": "300",
"rebcalc_towards_moving_cost_txt": "",
"rebcalc_towards_moving_cost_value": "100",
"session_length": "14400",
"signup_required_for_view_property_enable": "Yes",
"site_alternate_logo": "201605232336531482961313-logo.png",
"site_api_cache_enable": "No",
"site_cache_enable": "No",
"site_code_compression_enable": "Yes",
"site_currency": "$",
"site_description": "",
"site_domain": "",
"site_favicon": "201711170113101526416390-favicon.png",
"site_footer_logo": "201604190145481497717648-whoswho.png",
"site_logo": "201711170050201548526520-logo-new.png",
"site_max_full_details_without_login": "0",
"site_max_search_without_login": "0",
"site_name": "Site.com",
"site_print_logo": "201711170053401558958820-bw-logo.png",
"site_search_saver_display_after": "0",
"site_timestamp": "601",
"site_title": "Site.com",
"site_url": "https://www.site.com",
"summary_report_desclaimer": "",
"system_subtitle": "[Administrative Zone - CMS, CRM & Listing Management]",
"system_title": "Site.com - Website Content, Listing & Lead Management",
"thumb_big": "500x500",
"thumb_medium": "140x140",
"thumb_small": "50x50",
"total_page_allowed_before_registration": "2",
"track_email_open_interval": "1",
"twilio_account_sid": "",
"twilio_api_sid": "",
"twilio_friendly_name": "",
"twilio_key_type": "",
"twilio_registered_number": "",
"twilio_secret_token": "",
"valid_file_format": ".doc|.docx|.pdf|.txt",
"valid_pic_format": ".jpg|.jpeg|.png|.gif",
"valid_video_format": ".wmv|.avi|.mov|.swf",
"watermark_image": "watermark.png",
"why_site": "",
"yahoo_app_id": "123",
"yahoo_geocode_api_url": "",
"yahoo_map_api_url": "",
"yahoo_textextraction_api_url": "",
}