# Use an official Node.js runtime as a parent image
FROM node:18.17.0

# Set the working directory in the container


# Copy the current directory contents into the container at /nextjsapp/src/app


# Install any needed packages specified in package.json


# Build your Next.js application


# Make port 3000 available to the world outside this container


# Run npm start command when the container launches

